export default {
  weapon: {
    0: [
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
    ],
    150: [
      { stat: 0, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 11, atkAll: 8 },
      { stat: 11, atkAll: 9 },
      { stat: 11, atkAll: 9 },
      { stat: 11, atkAll: 10 },
      { stat: 11, atkAll: 11 },
      { stat: 11, atkAll: 12 },
      { stat: 11, atkAll: 13 },
    ],
    160: [
      { stat: 0, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 13, atkAll: 9 },
      { stat: 13, atkAll: 9 },
      { stat: 13, atkAll: 10 },
      { stat: 13, atkAll: 11 },
      { stat: 13, atkAll: 12 },
      { stat: 13, atkAll: 13 },
      { stat: 13, atkAll: 14 },
    ],
    200: [
      { stat: 0, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 15, atkAll: 13 },
      { stat: 15, atkAll: 13 },
      { stat: 15, atkAll: 14 },
      { stat: 15, atkAll: 14 },
      { stat: 15, atkAll: 15 },
      { stat: 15, atkAll: 16 },
      { stat: 15, atkAll: 17 },
    ],
  },
  equip: {
    0: [
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
    ],
    150: [
      { stat: 0, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 11, atkAll: 9 },
      { stat: 11, atkAll: 10 },
      { stat: 11, atkAll: 11 },
      { stat: 11, atkAll: 12 },
      { stat: 11, atkAll: 13 },
      { stat: 11, atkAll: 14 },
      { stat: 11, atkAll: 16 },
    ],
    160: [
      { stat: 0, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 13, atkAll: 10 },
      { stat: 13, atkAll: 11 },
      { stat: 13, atkAll: 12 },
      { stat: 13, atkAll: 13 },
      { stat: 13, atkAll: 14 },
      { stat: 13, atkAll: 15 },
      { stat: 13, atkAll: 17 },
    ],
    200: [
      { stat: 0, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 0 },
      { stat: 15, atkAll: 12 },
      { stat: 15, atkAll: 13 },
      { stat: 15, atkAll: 14 },
      { stat: 15, atkAll: 15 },
      { stat: 15, atkAll: 16 },
      { stat: 15, atkAll: 17 },
      { stat: 15, atkAll: 19 },
    ],
  },
  glove: {
    0: [
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
      { stat: 0, atkAll: 0 },
    ],
    150: [
      { stat: 0, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 1 },
      { stat: 11, atkAll: 9 },
      { stat: 11, atkAll: 10 },
      { stat: 11, atkAll: 11 },
      { stat: 11, atkAll: 12 },
      { stat: 11, atkAll: 13 },
      { stat: 11, atkAll: 14 },
      { stat: 11, atkAll: 16 },
    ],
    160: [
      { stat: 0, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 1 },
      { stat: 13, atkAll: 10 },
      { stat: 13, atkAll: 11 },
      { stat: 13, atkAll: 12 },
      { stat: 13, atkAll: 13 },
      { stat: 13, atkAll: 14 },
      { stat: 13, atkAll: 15 },
      { stat: 13, atkAll: 17 },
    ],
    200: [
      { stat: 0, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 0 },
      { stat: 2, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 0 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 1 },
      { stat: 3, atkAll: 1 },
      { stat: 15, atkAll: 12 },
      { stat: 15, atkAll: 13 },
      { stat: 15, atkAll: 14 },
      { stat: 15, atkAll: 15 },
      { stat: 15, atkAll: 16 },
      { stat: 15, atkAll: 17 },
      { stat: 15, atkAll: 19 },
    ],
  },
};
